### ISSUE TITLE
Poor synthetic audio quality

### ISSUE THREAD

**Issue by rgzn-aiyun** [ksw0306/FloWaveNet#14]
The training is as follows:
![image](https://user-images.githubusercontent.com/45959815/50332222-76c04700-053c-11e9-86a0-8af8922c4678.png)
Use the LJSpeech dataset, [Synthesized audio](https://github.com/rgzn-aiyun/Synthesized-audio)

**Comment by rgzn-aiyun** [comment]
@L0SG

**Comment by L0SG** [comment]
Assuming you are using default settings, the quality is expected since the training is an early state. Note that the quality progressively increases during the training, and there is a sharp quality bump after learning rate scaling (200K, 400K, etc).

**Comment by rgzn-aiyun** [comment]
@L0SG Thank you, How to synthesize speech in plain text?

**Comment by L0SG** [comment]
I'm afraid I cannot directly answer your question since TTS (assuming that you mean it) is too broad to cover for this repo. [Tacotron 2](https://ai.googleblog.com/2017/12/tacotron-2-generating-human-like-speech.html) might be a good starting point so I recommend you to check it out.
