### ISSUE TITLE
Do not understand where the text comes from

### ISSUE THREAD

**Issue by ls4cfk** [ksw0306/FloWaveNet#18]
Hi there,
 I want to change text for the output, generated wav file, any idea how? I was looking at the source but cannot figure out how does it work.. 

Thankies.

**Comment by L0SG** [comment]
Sorry for the late reply. The current scope of this repo is a general-purpose WaveNet vocoder (using Mel-spectrogram as the local condition like [Tacotron 2](https://arxiv.org/abs/1712.05884)). So this repo currently does not explicitly provide the entire TTS pipeline.
