### ISSUE TITLE
Equation (3) and (5) in paper and implementation

### ISSUE THREAD

**Issue by zhang-jian** [ksw0306/FloWaveNet#2]
Hi

Very nice work and thanks for sharing the code.

I have some questions about Equation (3) and (5) in your paper at https://arxiv.org/pdf/1811.02155.pdf. 

The forward transformation (Equation (3)) and reverse transformation (Equation (5)) are different than the ones in GLOW paper (Row 3, Table 1, https://arxiv.org/pdf/1807.03039.pdf). 

Their reverse function, such as `x = (y_a - t)/s`, is your forward function (implementation https://github.com/ksw0306/FloWaveNet/blob/master/model.py#L76) and Equation (3). 
Their forward function, such as `y = s*x_a + t`, matches your reverse function in implementation at https://github.com/ksw0306/FloWaveNet/blob/master/model.py#L90, but not Equation (5) on your paper.

Did I miss anything? Thanks

**Comment by ksw0306** [comment]
Sorry for the confusion. We immediately noticed the equation (5) is mistakenly copy-pasted from (3) (We were working around the clock for finalizing the ongoing draft). The reverse function you mentioned is indeed right (just like the implemented code). We'll fix the equation as soon as we finalize the v2 draft. Thank you for the correction!

**Comment by zhang-jian** [comment]
@ksw0306 Thanks, it is clear now.

**Comment by L0SG** [comment]
The v2 draft is out and we’ll close the issue. Thanks again!
