### ISSUE TITLE
Please add to the README how many seconds it takes to synthesize a sentence

### ISSUE THREAD

**Issue by vitaly-zdanevich** [ksw0306/FloWaveNet#21]
With GPU and without, on already trained model.

I want to use some open source text-to-speech on AWS Lambda, I am looking into some solutions that can render audio faster than real time.

**Comment by L0SG** [comment]
Sorry for the super late reply.

From our machine (2x Xeon E5-2690 v4), the CPU inference time is roughly from 5 to 7kHz. GPU inference time is around 370kHz on the TITAN V and 430K on the Tesla V100 (as stated in the paper).

Please note that we have not done inference optimizations in this repo (e.g. removing weight norm at inference and half-precision inference for the speed boost on Volta architecture using Tensor Cores).

**Comment by kwanUm** [comment]
Do you also have latency benchmark for your model on GPU? (e.g. what's the minimal chunk size it can process, what is the receptive field and necessary future context)
