### ISSUE TITLE
Command to generate synthesis from Tacotron-2 MELS ?

### ISSUE THREAD

**Issue by jmasterx** [ksw0306/FloWaveNet#23]
Hi

I am unable to figure out how to generate a synthesis with these parameters using the MELS spectrogram generated by Tacotron-2

parser.add_argument('--data_path', type=str, default='./DATASETS/ljspeech/', help='Dataset Path')
parser.add_argument('--sample_path', type=str, default='./samples', help='Sample Path')
parser.add_argument('--model_name', type=str, default='flowavenet', help='Model Name')
parser.add_argument('--num_samples', type=int, default=10, help='# of audio samples')
parser.add_argument('--load_step', type=int, default=0, help='Load Step')
parser.add_argument('--temp', type=float, default=0.8, help='Temperature')
parser.add_argument('--load', '-l', type=str, default='./params', help='Checkpoint path to resume / test.')
parser.add_argument('--n_layer', type=int, default=2, help='Number of layers')
parser.add_argument('--n_flow', type=int, default=6, help='Number of layers')
parser.add_argument('--n_block', type=int, default=8, help='Number of layers')
parser.add_argument('--cin_channels', type=int, default=80, help='Cin Channels')
parser.add_argument('--block_per_split', type=int, default=4, help='Block per split')
parser.add_argument('--num_workers', type=int, default=0, help='Number of workers')
parser.add_argument('--log', type=str, default='./log', help='Log folder.')

Where is the parameter for the MELS?

Does anyone have an example commandline?

Many Thanks
Joshua

**Comment by L0SG** [comment]
You can see from the [preprocessing.py](https://github.com/ksw0306/FloWaveNet/blob/master/preprocessing.py) that this repo uses a normalized version of the mel-spec on a decibel-scale (similar to [r9y9's wavenet_vocoder repo](https://github.com/r9y9/wavenet_vocoder)). The preprocessing pipeline in this repo is mostly hard-wired.

[NVIDIA's Tacotron 2 implementation](https://github.com/NVIDIA/tacotron2) uses a log-scale version of the mel-spec so it is not directly applicable unless you re-normalize them. You would need to train the model using the log-scale mel-spec to ensure the compatibility between them.
