### ISSUE TITLE
RuntimeError: Unknown error -1

### ISSUE THREAD

**Issue by hujinsen** [ksw0306/FloWaveNet#8]
hi, I run the following command, but got error during training. I don't konw why the training stopped.

### python train.py --model_name flowavenet --batch_size 1 --n_block 8 --n_flow 6 --n_layer 2 --causal no

Global Step : 47160, [4, 100] [Log pdf, Log p(z), Log Det] : [-4.071  -1.3882  5.4592]
Global Step : 47160, [4, 200] [Log pdf, Log p(z), Log Det] : [-3.8072 -1.3883  5.1956]
Global Step : 47160, [4, 300] [Log pdf, Log p(z), Log Det] : [-3.833  -1.3862  5.2192]
Global Step : 47160, [4, 400] [Log pdf, Log p(z), Log Det] : [-3.8035 -1.386   5.1895]
Global Step : 47160, [4, 500] [Log pdf, Log p(z), Log Det] : [-3.9065 -1.3802  5.2868]
Global Step : 47160, [4, 600] [Log pdf, Log p(z), Log Det] : [-3.7542 -1.3834  5.1376]
Global Step : 47160, [4, 700] [Log pdf, Log p(z), Log Det] : [-3.7565 -1.3889  5.1454]
Global Step : 47160, [4, 800] [Log pdf, Log p(z), Log Det] : [-3.9123 -1.3848  5.2971]
Global Step : 47160, [4, 900] [Log pdf, Log p(z), Log Det] : [-3.8986 -1.3856  5.2842]
Global Step : 47160, [4, 1000] [Log pdf, Log p(z), Log Det] : [-4.0164 -1.3854  5.4018]
Global Step : 47160, [4, 1100] [Log pdf, Log p(z), Log Det] : [-3.9558 -1.3868  5.3426]
Global Step : 47160, [4, 1200] [Log pdf, Log p(z), Log Det] : [-4.0773 -1.3795  5.4568]
Global Step : 47160, [4, 1300] [Log pdf, Log p(z), Log Det] : [-3.8799 -1.383   5.2629]
Evaluation Loss : -3.8945
Traceback (most recent call last):
  File "train.py", line 241, in <module>
    save_checkpoint(model, optimizer, global_step, epoch)
  File "train.py", line 185, in save_checkpoint
    "global_epoch": global_epoch}, checkpoint_path)
  File "/home/hu/anaconda3/envs/hhh/lib/python3.6/site-packages/torch/serialization.py", line 209, in save
    return _with_file_like(f, "wb", lambda f: _save(obj, f, pickle_module, pickle_protocol))
  File "/home/hu/anaconda3/envs/hhh/lib/python3.6/site-packages/torch/serialization.py", line 134, in _with_file_like
    return body(f)
  File "/home/hu/anaconda3/envs/hhh/lib/python3.6/site-packages/torch/serialization.py", line 209, in <lambda>
    return _with_file_like(f, "wb", lambda f: _save(obj, f, pickle_module, pickle_protocol))
  File "/home/hu/anaconda3/envs/hhh/lib/python3.6/site-packages/torch/serialization.py", line 288, in _save
    serialized_storages[key]._write_file(f, _should_read_directly(f))
RuntimeError: Unknown error -1

**Comment by L0SG** [comment]
Apparently the error has been raised during saving the model. We've not experienced this kind of error and we think the code itself is fine (we're running the code with multiple HW setups).

My initial suspect is [out of your disk space](https://discuss.pytorch.org/t/runtime-error-on-saving-the-module/15179).
